version: '3'
services:
  structurizr:
    image: structurizr/lite
    volumes:
      - ./docs/structurizr/src:/usr/local/structurizr
    ports:
      - 8080:8080

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: auth
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - backend

  auth-service:
    build: ./apps/auth-service
    ports:
      - 8081:8081
    depends_on:
      - auth-db
    networks:
      - backend
      
networks:
    backend:
        driver: bridge
