name: UI Continuous Integration

on:
  push:
    paths:
      - 'packages/ui/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/ui/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build
        run: |
          cd packages/ui
          npm ci
          npm run build